version: '3'
services:
  app:
    container_name: nodemon-watch-issue-app
    image: "node:12"
    user: "node"
    working_dir: "/home/node/app"
    volumes:
      - "./:/home/node/app:ro"
    command: "npm run start:legacy"
